name: Label PR based on Branch Name

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Get Branch Name
        id: branch_name
        run: echo "::set-output name=name::$(echo $GITHUB_REF | cut -d'/' -f 3)"
        
      - name: Label PR
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = '${{ steps.branch_name.outputs.name }}';
            const prefix = branchName.split('-')[0];
            const labelsToAdd = [prefix];
            await github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: labelsToAdd
            });
