name: Label PR based on Branch Name

on:
  pull_request:
    types: [opened]
  label:
    types: [created, deleted]

jobs:
  label_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR from branchname
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
             console.log(JSON.stringify(context));
             const branchName =  context.payload.pull_request.head.ref;
             console.log('Branch Name:', branchName);
             const prefix = branchName.split('/')[0];
             console.log('Prefix:', prefix);
             const labelsToAdd = ["bug", "feat", "ignore"];
             if (labelsToAdd.includes(prefix)) {
               console.log('Adding label:', prefix);
               await github.rest.issues.addLabels({
                 issue_number: context.issue.number,
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 labels: [prefix]
               });
             } else {
               console.log('No matching label found for prefix:', prefix);
             }
      - name: Verify relevant label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const releaseLabels = [
                "breaking-change",
                "feature",
                "bugfix",
                "dependency", 
                "ignore-for-release",
                ];
            const labels = await github.rest.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            )).map(l=>l.name);
            
            if(!labels.some(label=>{
              releaseLabels.indexOf(label) != -1
            })
            {
              core.setFailed('Pull request is missing label for release notes');
            }
            
